apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mb5rrnh1k-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-28caab51bf.b5uv.p3.openshiftapps.com/rhtap/rhtap-qe:6ef36c2e38c4940e6ea6e0305e735c3248dfe6b2@sha256:8a4ae5434a854e8d6c65a48e170907fe13f304536fe041806a9a88d6a0d88484
          name: container-image
